FROM golang:1.15-alpine as builder

RUN apk update \
    && apk upgrade \
    && apk add --no-cache git bash make \
    && mkdir -p /client

WORKDIR /client

COPY go.mod go.sum ./

RUN go mod download

ADD . .

ARG DEMO

RUN go build -o postclient ./cmd/${DEMO}/main.go

## FINAL IMAGE
FROM alpine as app

WORKDIR /

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /client/postclient .

RUN chmod +x ./postclient

EXPOSE 8080

CMD ["/postclient"]