apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo2
  labels:
    app: server-demo2
  name: server-demo2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server-demo2
  template:
    metadata:
      labels:
        app: server-demo2
    spec:
      containers:
      - image: server:latest
        name: server-demo2
        imagePullPolicy: Never
