apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo3
  labels:
    app: proxy-demo3
  name: proxy-demo3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-demo3
  template:
    metadata:
      labels:
        app: proxy-demo3
    spec:
      containers:
      - image: h2-local-proxy:latest
        name: proxy-demo3
        imagePullPolicy: Never
