apiVersion: v1
kind: Service
metadata:
  namespace: demo3
  labels:
    app: svc-proxy
  name: svc-proxy
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http-port
    port: 50060
    protocol: TCP
    targetPort: 50060
  selector:
    app: proxy-demo3
