apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo3
  labels:
    app: server-demo3
  name: server-demo3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server-demo3
  template:
    metadata:
      labels:
        app: server-demo3
    spec:
      containers:
      - image: server:latest
        name: server-demo3
        imagePullPolicy: Never
