apiVersion: v1
kind: Service
metadata:
  namespace: demo3
  labels:
    app: svc-server
  name: svc-server
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: grpc-port
    port: 50051
    protocol: TCP
    targetPort: 50051
  selector:
    app: server-demo3
