apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo3
  labels:
    app: client-demo3
  name: client-demo3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-demo3
  template:
    metadata:
      labels:
        app: client-demo3
    spec:
      containers:
      - image: demo3:latest
        name: client-demo3
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: client-demo3-config
