apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo1
  labels:
    app: server-demo1
  name: server-demo1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server-demo1
  template:
    metadata:
      labels:
        app: server-demo1
    spec:
      containers:
      - image: server:latest
        name: server-demo1
        imagePullPolicy: Never
