apiVersion: v1
kind: Service
metadata:
  namespace: demo1
  labels:
    app: svc-server
  name: svc-server
spec:
  ports:
  - name: grpc-port
    port: 50051
    protocol: TCP
    targetPort: 50051
  selector:
    app: server-demo1
